### ISSUE TITLE
APK or demo?

### ISSUE THREAD

**Issue by vishalv26** [realdiganta/hitup-messenger#2]
Hi,

is there any APK or demo of the app?

What is used for OTP?

How scalable it is? any bugs?

**Comment by dxganta** [comment]
APK or demo: Yes there is a version of it launched at https://play.google.com/store/apps/details?id=com.digantakalita.coocoo . The playstore version has been modified a little bit for private messaging.

OTP: Firebase Authentication

Scalable: Very much. Used MQTT for messaging. Firestore for user DB. Local SQFLITE DB for storing user messages. And highly efficient algorithms for contact retrieval and stuff.

Bugs: Not any that I know of currently.

**Comment by vishalv26** [comment]
I think the service is down. It is showing blank hitup id. And also the whatsapp number mentioned in help is not on whatsapp

**Comment by dxganta** [comment]
Can you send a screenshot of the error "blank hitup id" and where it is occuring exactly.

**Comment by vishalv26** [comment]
wanna connect on whatsapp? i have a plan?

**Comment by dxganta** [comment]
hit me an email: digantakalita.ai@gmail.com
